version: '2.1'

services:
  node:
    build: 
     context: .
     dockerfile: ./nodeJS/Dockerfile
    container_name: nextepc-webui
    network_mode: host
    ports:
     - "3000:3000"

  mongodb:
    build:
     context: .
     dockerfile: ./mongoDB/Dockerfile
    container_name: nextepc-mongodb
    network_mode: host
    ports:
     - "27017:27017"
    volumes:
     - ./mongodata:/data/db


  vepc:
    build:
     context: .
     dockerfile: ./vEPC/Dockerfile
    container_name: nextepc-vepc
    depends_on:
     - node
    ports:
     - "27017:27017"
    cap_add:
     - SYS_ADMIN
     - NET_ADMIN
    network_mode: host
    sysctls:
     - net.ipv6.conf.all.disable_ipv6=0
    devices:
     - "/dev/net/tun:/dev/net/tun"
    privileged: true
    hostname: nextepc
    volumes:
     - ./mongodata:/data/db
    command: /bin/bash -c "chmod 666 /dev/net/tun"

